# Generated by Django 2.0.2 on 2018-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
